name: Docker Image

on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - ".editorconfig"
  pull_request:
  schedule:
    - cron: 0 9 1-7,21-28 * 3

jobs:
  docker-image-windows:
    strategy:
      matrix:
        windows:
          - image: servercore
            version: ltsc2022
            runs_on: 2022
          - image: servercore
            version: ltsc2025
            runs_on: 2025
        nsis:
          # https://sourceforge.net/projects/nsis/files/NSIS%203/3.12/
          - version: "3.12"
            version_minor: "3.12"
            version_major: "3"

    env:
      IMAGE_NAME_FULL: "fabiang/nsis:${{ matrix.nsis.version }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"
      IMAGE_NAME_MINOR: "fabiang/nsis:${{ matrix.nsis.version_minor }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"
      IMAGE_NAME_MAJOR: "fabiang/nsis:${{ matrix.nsis.version_major }}-windows${{ matrix.windows.image }}-${{ matrix.windows.version }}"

    runs-on: windows-${{ matrix.windows.runs_on }}

    continue-on-error: true
    environment: prod

    name: "Win v${{ matrix.nsis.version }} (${{ matrix.windows.image }} – ${{ matrix.windows.version }})"

    steps:
      - uses: actions/checkout@v3

      # Githubs Cache with 10GB is to small
      #      - uses: jpribyl/action-docker-layer-caching@v0.1.1
      #        continue-on-error: true

      - name: Build Image
        run: |
          docker build -f windows/Dockerfile `
            -t '${{ env.IMAGE_NAME_FULL }}' `
            `
            --build-arg 'NSIS_VERSION=${{ matrix.nsis.version }}' `
            `
            --build-arg 'WINDOWS_IMAGE=${{ matrix.windows.image }}' `
            --build-arg 'WINDOWS_VERSION=${{ matrix.windows.version }}' `
            .

      - name: Tag Minor
        if: "${{ matrix.nsis.version_minor != '' && matrix.nsis.version != matrix.nsis.version_minor }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.nsis.version_major != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'

      - name: Test Image
        run: |
          docker run --rm -v "${{ github.workspace }}/tests/gui_app:C:\app" `
            -w C:\app `
            --entrypoint='' `
            '${{ env.IMAGE_NAME_FULL }}' `
            makensis.exe test.nsi

      - name: Docker Hub login
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: azure/docker-login@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'

      - name: Push Image Minor
        if: "${{ matrix.nsis.version_minor != '' && matrix.nsis.version != matrix.nsis.version_minor && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'

      - name: Push Image Major
        if: "${{ matrix.nsis.version_major != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'

  docker-image-alpine:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        nsis:
          - version: "3.12"
            version_minor: "3.12"
            version_major: "3"
            download_hash: "f3ed7a8e4aa2cf4e8cf47d3b563a02559e0cb4934db2662b2f9661b824e2b186"

    env:
      IMAGE_NAME_FULL: "fabiang/nsis:${{ matrix.nsis.version }}-alpine"
      IMAGE_NAME_MINOR: "fabiang/nsis:${{ matrix.nsis.version_minor }}-alpine"
      IMAGE_NAME_MAJOR: "fabiang/nsis:${{ matrix.nsis.version_major }}-alpine"

    name: "Alpine v${{ matrix.nsis.version }}"

    environment: prod

    steps:
      - uses: actions/checkout@v3

      - name: Build Image
        run: |
          docker build -f alpine/Dockerfile \
            -t '${{ env.IMAGE_NAME_FULL }}' \
            --build-arg 'NSIS_VERSION=${{ matrix.nsis.version }}' \
            --build-arg 'NSIS_SOURCE_HASH=${{ matrix.nsis.download_hash }}' \
            .

      - name: Tag Minor
        if: "${{ matrix.nsis.version_minor != '' && matrix.nsis.version != matrix.nsis.version_minor }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MINOR }}'

      - name: Tag Major
        if: "${{ matrix.nsis.version_major != '' }}"
        run: docker tag '${{ env.IMAGE_NAME_FULL }}' '${{ env.IMAGE_NAME_MAJOR }}'

      - name: Test Image
        run: |
          docker run --rm -v "${{ github.workspace }}/tests/gui_app:/app" \
            -w /app \
            --entrypoint='' \
            '${{ env.IMAGE_NAME_FULL }}' \
            makensis test.nsi

      - name: Docker Hub login
        if: "${{ github.ref == 'refs/heads/main' }}"
        uses: azure/docker-login@v2
        with:
          username: ${{ secrets.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Push Image
        if: "${{ github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_FULL }}'

      - name: Push Image Minor
        if: "${{ matrix.nsis.version_minor != '' && matrix.nsis.version != matrix.nsis.version_minor && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MINOR }}'

      - name: Push Image Major
        if: "${{ matrix.nsis.version_major != '' && github.ref == 'refs/heads/main' }}"
        run: |
          docker push '${{ env.IMAGE_NAME_MAJOR }}'
